name: Netlify Deployment Status Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  deployment-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run deployment check
        id: deployment-check
        run: |
          code=$(curl -s -o /dev/null -w "%{http_code}" https://info-dashboard-template.netlify.app/)
          if [[ $code != 200 ]]; then
            exit 1
          fi
