name: Test

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows running this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Contains a single job called "build"
  deployment-check:
    runs-on: ubuntu-latest
    steps:
      # Checks out repository under $GITHUB_WORKSPACE, so job can access it
      - uses: actions/checkout@v2

      - name: Run deployment check
        id: deployment-check
        run: curl -s -o /dev/null -w "%{http_code}" https://info-dashboard-template.netlify.app/
        
      - name: Return Status check
        if: steps.deployment-check.outcome == '200'
        run: echo 'SUCCESS'

